// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCadQLmXSXzVJ9fuLvXLPoQ5h4pj7yLAqk',
    appId: '1:83134433889:web:c52d54514b7a2723dff820',
    messagingSenderId: '83134433889',
    projectId: 'e-commerce-admin-user',
    authDomain: 'e-commerce-admin-user.firebaseapp.com',
    storageBucket: 'e-commerce-admin-user.firebasestorage.app',
    measurementId: 'G-J1FCTQYTSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRtC_xeoiiN2ouBZW8DZlS38k0tSrVto4',
    appId: '1:83134433889:android:388777407e818b4cdff820',
    messagingSenderId: '83134433889',
    projectId: 'e-commerce-admin-user',
    storageBucket: 'e-commerce-admin-user.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo6ToV4JtBA0beufSvxHpqmssWFnzaAlM',
    appId: '1:83134433889:ios:037f4e706907b2a3dff820',
    messagingSenderId: '83134433889',
    projectId: 'e-commerce-admin-user',
    storageBucket: 'e-commerce-admin-user.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo6ToV4JtBA0beufSvxHpqmssWFnzaAlM',
    appId: '1:83134433889:ios:037f4e706907b2a3dff820',
    messagingSenderId: '83134433889',
    projectId: 'e-commerce-admin-user',
    storageBucket: 'e-commerce-admin-user.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCadQLmXSXzVJ9fuLvXLPoQ5h4pj7yLAqk',
    appId: '1:83134433889:web:d23f5140eaa24f59dff820',
    messagingSenderId: '83134433889',
    projectId: 'e-commerce-admin-user',
    authDomain: 'e-commerce-admin-user.firebaseapp.com',
    storageBucket: 'e-commerce-admin-user.firebasestorage.app',
    measurementId: 'G-DM6MHF3NT0',
  );
}
